/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function fibonacci(n: number): number
export function mergeSort(arr: Array<number>): Array<number>
export function quickSort(arr: Array<number>): Array<number>
export function sum(a: number, b: number): number
export function nativeSort(arr: Array<number>): Array<number>
export function bubbleSort(arr: Array<number>): Array<number>
